---
title: "Dsata_descriptions"
output: html_document
date: "2023-10-18"
---

```{r}
library(readxl)
library(openxlsx)
library(dplyr)
library(stringr)
library(lubridate)
library(hms)
library(DescTools)
library(eeptools)
library(ggplot2)
library(data.table)
```

```{r}
# Load file
icu_stays <- read.csv('../MIMIC/ICUSTAYS.csv/ICUSTAYS.csv')
admission <- read.csv('../MIMIC/ADMISSIONS.csv/ADMISSIONS.csv')
patients <- read.csv('../MIMIC/PATIENTS.csv/PATIENTS.csv')
```

```{r}
# patient exploration (age, gender, ethnicity)
gender <- data.frame(cbind(patients$SUBJECT_ID , patients$GENDER))
colnames(gender) <- c('SUBJECT_ID', 'GENDER')

admission_dates <- data.frame(cbind(admission$SUBJECT_ID, admission$ADMITTIME)) #THERE ARE MUTIPLE HOSPITAL ADMISSIONS FOR SOME PATIENTS
colnames(admission_dates) <- cbind('SUBJECT_ID', 'ADMIT_DATE')
admission_dates$ADMIT_DATE <- as.Date(admission_dates$ADMIT_DATE)
admission_dates_new <- setDT(admission_dates)[order(admission_dates$ADMIT_DATE), head(.SD, 1L), by = SUBJECT_ID] # only the first hospital admission is kept

dob <- data.frame(cbind(patients$SUBJECT_ID, patients$DOB))
colnames(dob) <- c('SUBJECT_ID', 'DOB')
dob$DOB <- as.Date(dob$DOB)

dates <- merge(admission_dates_new, dob, by = "SUBJECT_ID")
age <- data.frame(age_calc(dates$DOB, dates$ADMIT_DATE, units = "years"))
age <- data.frame(cbind(dates$SUBJECT_ID, age))
colnames(age) <- c('SUBJECT_ID', 'AGE')
age$AGE <- floor(as.numeric(age$AGE))

ethn <- data.frame(cbind(admission$SUBJECT_ID, admission$ETHNICITY))
colnames(ethn) <- cbind('SUBJECT_ID', 'ETHNICITY')
ethn <- ethn[!duplicated(ethn), ]
rownames(ethn) <- seq(1, nrow(ethn), by=1)

```

```{r}
age_new <- age
id_300_idx <- which(age_new$AGE == 300)
age_new$AGE[id_300_idx] <- 'N/A'

id_0_idx <- which(age_new$AGE == 0)
age_new$AGE[id_0_idx] <- '<1'
```

```{r}
ethn_new <- ethn 
for (i in 1:nrow(ethn_new)){
  if (substr(ethn_new$ETHNICITY[i], 1, 5) == "ASIAN"){
    ethn_new$ETHNICITY[i] <- "ASIAN"
  }
  
  if (substr(ethn_new$ETHNICITY[i], 1, 15) == "HISPANIC/LATINO"){
    ethn_new$ETHNICITY[i] <- "HISPANIC OR LATINO"
  }
  
  if (substr(ethn_new$ETHNICITY[i], 1, 5) == "WHITE"){
    ethn_new$ETHNICITY[i] <- "WHITE"
  }
  if (substr(ethn_new$ETHNICITY[i], 1, 5) == "BLACK"){
    ethn_new$ETHNICITY[i] <- "BLACK"
  }
  if (substr(ethn_new$ETHNICITY[i], 1, 29) == "AMERICAN INDIAN/ALASKA NATIVE"){
    ethn_new$ETHNICITY[i] <- "AMERICAN INDIAN/ALASKA NATIVE"
  }
  if (ethn_new$ETHNICITY[i] == "MIDDLE EASTERN"){
    ethn_new$ETHNICITY[i] <- "WHITE"
  }
  if (ethn_new$ETHNICITY[i] == "PORTUGUESE"){
    ethn_new$ETHNICITY[i] <- "WHITE"
  }
  
}

ethn_new <- unique(ethn_new)
  
  
```

```{r}
write.csv(gender, "gender.csv")
write.csv(age_new, "age.csv")
write.csv(ethn_new, "ethnicity.csv")
```

```{r}
age_nonval_idx <- which(data.frame(is.na(as.numeric(age_new$AGE)))[,1] == "TRUE")
mean_age <- mean(as.numeric(age_new[-age_nonval_idx,]$AGE))
std_age <- sd(as.numeric(age_new[-age_nonval_idx,]$AGE))
range_age <- range(as.numeric(age_new[-age_nonval_idx,]$AGE))
```

```{r}
gender_freq <- data.frame(table(gender$GENDER))
colnames(gender_freq) <- c('GENDER', 'GENDER_FREQ')
gender_plot <- ggplot(gender_freq, aes(x = factor(GENDER), y = GENDER_FREQ)) + geom_col(width = 0.4) + xlab('Gender') + ylab('Gender Frequency') + ggtitle('Frequency of patient gender')
gender_plot

age_freq <- data.frame(table(age_new$AGE))
colnames(age_freq) <- c('AGE', 'AGE_FREQ')
age_plot <- ggplot(age_freq, aes(x = factor(AGE), y = AGE_FREQ)) + geom_col(width = 0.7) + scale_x_discrete(guide = guide_axis(n.dodge = 2)) + xlab('Age (years old)') + ylab('Age Frequency') + ggtitle('Frequency of patient age') + theme(axis.text.x = element_text(angle = 0, size = 6))
age_plot

ethn_freq <- data.frame(table(ethn_new$ETHNICITY))
colnames(ethn_freq) <- c('ETHN', 'ETHN_FREQ')
# ethn_plot <- ggplot(ethn_freq, aes(x = factor(ETHN), y = ETHN_FREQ)) + geom_col(width = 0.4) + xlab('Ethnicity') + ylab('Ethnicity Frequency') + ggtitle('Frequency of patient ethnicity') + theme(axis.text.x = element_text(angle = 90, vjust = 0.1, hjust = 0.3), text = element_text(size = 8)) + scale_x_discrete(labels = function(x) str_wrap(x, width = 17)) + geom_text(aes(label = ETHN_FREQ), vjust = 0, colour = "black")
ethn_plot <- ggplot(ethn_freq, aes(x = factor(ETHN), y = ETHN_FREQ)) + geom_col(width = 0.4) + xlab('Ethnicity') + ylab('Ethnicity Frequency') + ggtitle('Frequency of patient ethnicity') + theme(axis.text.x = element_text(angle = 90, vjust = 0.1, hjust = 0.3), text = element_text(size = 8)) + scale_x_discrete(labels = function(x) str_wrap(x, width = 17)) 
ethn_plot

ggsave(filename="gender_plot.jpg", plot=gender_plot)
ggsave(filename="age_plot.jpg", plot=age_plot)
ggsave(filename="ethnicity_plot.jpg", plot=ethn_plot)

```


```{r}
# ICU stays / person
# extract subject ID
icu_subject_id <- data.frame(icu_stays$SUBJECT_ID)
colnames(icu_subject_id) <- 'SUBJECT_ID'

unique_icu_stay <- data.frame(table(icu_subject_id))
colnames(unique_icu_stay) <- c('SUBJECT_ID', 'icu_stay_freq')

icu_patient_number <- unique(icu_subject_id)
```

```{r}
# extract ICU start and stop time
icu_stay_id <- icu_stays$ICUSTAY_ID
icu_stay_id <- data.frame(icu_stay_id)
icu_admission_start_time <- icu_stays$INTIME
icu_admission_start_time <- data.frame(icu_admission_start_time)
icu_admission_stop_time <- icu_stays$OUTTIME
icu_admission_stop_time <- data.frame(icu_admission_stop_time)

# length of each ICU stay
icu_stop <- strptime(icu_admission_stop_time$icu_admission_stop_time, "%Y-%m-%d %H:%M:%S")
icu_start <- strptime(icu_admission_start_time$icu_admission_start_time, "%Y-%m-%d %H:%M:%S")
icu_admission_length <- data.frame(as.numeric(difftime(icu_stop, icu_start), units = "secs"))
colnames(icu_admission_length) <- 'icu_admission_length'
icu_admission_length <- data.frame(as.character(seconds_to_period(icu_admission_length$icu_admission_length)))
colnames(icu_admission_length) <- 'icu_admission_length'

icu_data <- cbind(icu_subject_id, icu_stay_id, icu_admission_start_time, icu_admission_stop_time, icu_admission_length)

icu_data_timefreq <- merge(icu_data, unique_icu_stay, by = "SUBJECT_ID")
write.csv(icu_data_timefreq, "icu_data_with_time_and_freq.csv")
```

```{r}
# hospital admission / person
# extract subject ID
hospital_subject_id <- data.frame(admission$SUBJECT_ID)
colnames(hospital_subject_id) <- 'SUBJECT_ID'
unique_hospital_admission <- data.frame(table(hospital_subject_id))
colnames(unique_hospital_admission) <- c('SUBJECT_ID', 'hospital_admission_freq')

hospital_unique_patient <- unique(hospital_subject_id)
hospitaladmission <- unique(admission$HADM_ID)
icuadmission <- unique(icu_stays$ICUSTAY_ID)
```

```{r}
# extract subject ID, ADMITTIME, DISCHTIME
hospital_admission_id <- admission$HADM_ID
hospital_admission_id <- data.frame(hospital_admission_id)
hospital_admission_time <- admission$ADMITTIME
hospital_admission_time <- data.frame(hospital_admission_time)
hospital_discharge_time <- admission$DISCHTIME
hospital_discharge_time <- data.frame(hospital_discharge_time)

# length of hospital admission
hospital_discharge <- strptime(hospital_discharge_time$hospital_discharge_time, "%Y-%m-%d %H:%M:%S")
hospital_start <- strptime(hospital_admission_time$hospital_admission_time, "%Y-%m-%d %H:%M:%S")
hospital_admission_length <- data.frame(as.numeric(difftime(hospital_discharge, hospital_start), units = "secs"))
colnames(hospital_admission_length) <- 'hospital_admission_length'
hospital_admission_length <- data.frame(as.character(seconds_to_period(hospital_admission_length$hospital_admission_length)))
colnames(hospital_admission_length) <- 'hospital_admission_length'

hospital_data <- cbind(hospital_subject_id, hospital_admission_id, hospital_admission_time, hospital_discharge_time, hospital_admission_length)

hospital_data_timefreq <- merge(hospital_data, unique_hospital_admission, by = "SUBJECT_ID")
write.csv(hospital_data_timefreq, "hospital_data_with_timefreq.csv")
```

```{r}
hospital_data_timefreq_nondup <- hospital_data_timefreq[!duplicated(hospital_data_timefreq[c('SUBJECT_ID')]), ]

icu_data_timefreq_nondup <- icu_data_timefreq[!duplicated(icu_data_timefreq[c('SUBJECT_ID')]), ]
```

```{r}
hospital_freq <- data.frame(table(hospital_data_timefreq_nondup$hospital_admission_freq))
colnames(hospital_freq) <- c('hospital_admissions', 'hospital_freq')
hospital_freq_plot <- ggplot(hospital_freq, aes(x = factor(hospital_admissions), y = hospital_freq)) + geom_col(width = 0.7)  + xlab('Hospital Admissions (times)') + ylab('Hospital Admission Frequency') + ggtitle('Frequency of patient hospital admissions') + geom_text(aes(label = hospital_freq), vjust = -0.5, colour = "black", size = 2.7)
hospital_freq_plot

icu_freq <- data.frame(table(icu_data_timefreq_nondup$icu_stay_freq))
colnames(icu_freq) <- c('icu_stays', 'icu_freq')
icu_freq_plot <- ggplot(icu_freq, aes(x = factor(icu_stays), y = icu_freq)) + geom_col(width = 0.7)  + xlab('ICU Admissions (times)') + ylab('ICU Admission Frequency') + ggtitle('Frequency of patient icu admissions') + geom_text(aes(label = icu_freq), vjust = -0.5, colour = "black", size = 2.7)
icu_freq_plot

ggsave(filename="hospital_freq_plot.jpg", plot=hospital_freq_plot)
ggsave(filename="icu_freq_plot.jpg", plot=icu_freq_plot)
```

```{r}
not_one_time_hospital <- hospital_data_timefreq[which(hospital_data_timefreq$hospital_admission_freq != 1),]
not_one_time_icu <- icu_data_timefreq[which(icu_data_timefreq$icu_stay_freq != 1),]
```

```{r}
combined_data <- merge(hospital_data_timefreq, icu_data_timefreq, by = "SUBJECT_ID")
write.csv(combined_data, "hospital_icu_data.csv")

```

```{r}
combined_data <- read.csv("hospital_icu_data.csv")
combined_data <- combined_data[-1]
```

```{r}
# combine hospital and ICU data with creatinine measurement data
combined_data_with_creatinine <- merge(combined_data, creatinine_data, by = "SUBJECT_ID")
```

```{r}
# number of ICU admissions that have creatinine measurements
icu_with_creatinine <- data.frame(unique(combined_data_with_creatinine$icu_stay_id))
colnames(icu_with_creatinine) <- 'icu_stay_id'

# number of hospital admissions that have creatinine measurements 
hospital_with_creatinine <- data.frame(unique(combined_data_with_creatinine$hospital_admission_id))
colnames(hospital_with_creatinine) <- 'hospital_admissino_id'

# number of subjects that have creatinine measurements
subject_with_creatinine <- data.frame(unique(combined_data_with_creatinine$SUBJECT_ID))
colnames(subject_with_creatinine) <- 'SUBJECT_ID'

```

```{r}
# number of "creatinine" measurements available for each subject-hospital admission
unique_creatinine_hospital <- data.frame(table(combined_data_with_creatinine$hospital_admission_id))
colnames(unique_creatinine_hospital) <- c('hospital_admission_id', 'creatinine_freq_per_hospital')

# combined_data_with_creatinine <- merge(combined_data_with_creatinine, unique_creatinine_hospital, by = "hospital_admission_id")

```

```{r}
# divide ICU to 24 hour blocks
# icu_data_new <- data.frame(matrix(ncol = 0, nrow = nrow(icu_data)))
for (i in 4){
  icu_time_segments <- seq(as.numeric(as.POSIXct(icu_data$icu_admission_start_time[i])), 
                         as.numeric(as.POSIXct(icu_data$icu_admission_stop_time[i])),
                         by = 24*3600)
  icu_time_segments <- data.frame(t(as.character(as.POSIXct(icu_time_segments))))
  cbind(icu_data[i,], icu_time_segments)
}


```




